### PR TITLE
V1.5

### PR DESCRIPTION
**Pull request by 183amir**

### CODE REVIEW

**Comment by ocefpaf** [comment]
@183amir please add a description to this thread explaining the need for this version. (For provenance sake.) Also, can you add yourself as maintainer? At least for this version, but v2 as well if you wish to do so.

**Comment by 183amir** [comment]
I need this to compile ffmpeg with openjpeg support: https://github.com/conda-forge/ffmpeg-feedstock/pull/3

**Comment by ocefpaf** [comment]
@conda-forge-admin we need to
- [ ] update the [wiki](https://github.com/conda-forge/staged-recipes/wiki/Pinned-dependencies) pining `openjepg 2*` (or `openjepg 2.1.*`?);
- [ ] update the pinning to all but `ffmpeg`;
- [ ] pin `ffmpeg` to the older version (`openjepg 1.*`).

Bare in mind that this will prevent the installation of `ffmpeg` with the rest of the stack! Not sure if we should just rename the `lib` here to allow an along side installation.

**Comment by 183amir** [comment]
I am not sure that is a good idea. Maybe you can hold this pull until we figure things out.
My main concern is this issue: https://github.com/conda-forge/ffmpeg-feedstock/issues/2 which now seems to be related to zlib.

**Comment by 183amir** [comment]
My problem was related to `zlib` not `openjpeg` so I will close this pull but adding `openjpeg1` as a separate package seems like a good idea to me.

**Pull request closed without merging**
